baseURL = "https://blog.earo.me/"
languageCode = "en-us"
title = "epsilon"
theme = "yinwang"
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = false
#pygmentsStyle = "dracula"
#pygmentsOptions = ['linenos']

[params]
    author = "Earo Wang"
    github = "earowang"
    aboutme = "earo.me"
    googleAnalytics = "UA-83007123-2"
    disqusShortname = "earowang"
    ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "^data$"]
    highlight = "github"
    langs = ["r", "yaml"]
    # single = false
    menus = true
    # backgroundColor = "#fbf6ec"
    
[Permalinks]
    post = "/:year/:month/:day/:filename/"
