---
title: "ggplot2 and the grammar of graphics"
description: "Thoughts on 'The grammar of graphics'"
draft: true
date: "`r Sys.Date()`"
tags: ["book", "graphics"]
---

*ggplot2* has probably been a standard tool to craft statistical graphics in the R community over years. If one is asked why using *ggplot2*, you may receive answers like "it makes graphs look pretty". *ggplot2* is yet more than that. The first two letters *gg* is the abbreviation of "grammar of graphics", which implies that there's statistical thinking underlying plots. This framework originated from Leland Wikinson who wrote the book **The Grammar of Graphics** in 1999, and was further developed and implemented by Hadley Wickham, the author of *ggplot2*. **The Grammar of Graphics** is not constrained to graphics, but sheds light on a broad range of topics including objected oriented design (OOD), data structure, statistics, and etc. Wikinson's book on graphic grammar and variable mappings fuels the flourish of *ggplot2* and the *tidyverse* ecosystem; for example, *ggplot2* adapts the OOD approach to ensure the elegant programming and the hassle-free extension of the package as long as graphics are clearly defined by grammatical rules. This post is intended to give a glimpse at the grammar of graphics and discuss the differences between the theory (the book) and the practice (*ggplot2*).

## Graphics vs charts

> What is a pie chart? 
>
> Hmm, a pie chart is ... (thinking hard `r emo::ji("thinking")`, and a couple minutes later) Oh, do you mean a pie plus a chart? `r emo::ji("wink")`

This sort of conversation occurred to me, and I didn't know how to actually describe a pie chart at that moment. Well, I knew how to read a pie but was unaware of what defines it and how to make it from scratch. Although the conversation was brief and short, it made me get started with **The Grammar of Graphics**.

Many terms have been invented for this and that graphics, such as pie charts, histograms, rose plots, and so on. The vocabulary bank will expand as new charts are created. It's not a problem about the increased number of new words, but our understanding of graphics would remain shallow if simply using the *building-vocabulary* approach. These terms could also be a hindrance in spotting the differences between two kinds of charts. For example, what's the difference between pie charts and stacked bar charts? If it takes some time to figure out an answer, here's indeed the ground where the grammar of graphics pops in and sparks off. **A pie is a stacked bar in polar coordinates.** How straightforward it is! But the statement is made from a graphic perspective rather than a chart view. A graphic can be decomposed into a set of instances of graphics including geometry, scales, coordinates, and etc. By doing so, it provides shorthand but comprehensive vocabulary to describe and create an array of various graphics. To make a pie,

The grammar lends itself to OOD.

## Data structure
